### PR TITLE
New zombie variant, other changes

### PR DESCRIPTION
**Pull request by mwbullen**

### CODE REVIEW

**Comment by BHD7** [comment]
Mike - I love the end screen. Great addition. And the fire zombies are cool. Why is the day cycle so short? I get killed quickly every time.

I was able to fix the odd issue with the text on the street signs and highway sign. Not sure how that happened. And I keep playing around with adding weapons and ammo... Did you know we have grenades? Nice! Maybe we can put them in some of the destructible crates. That would be cool. It is always fun to break stuff and get loot.  😃

Other possible game modes:
- nightmare (always night, more zombies, more weapons)
- exploration (really long day cycles, fewer zombies, more stuff to discover)
- rockslide (you have to find parts of a bomb and place them together at the rocks near the exit before you can leave / win - move the win area to the other side of the rocks)
- power ups galore (there are a bunch of funny power ups built into UFPS like super speed and others that might be fun)
- running man (turn the running option back on)
- survivalist (no weapons besides the knife, axe or other meter weapons)

Speaking of which, it is apparently fairly easy to swap a knife for an ax or other never weapons. There are videos on YouTube showing how to do it. And I think it's also on the UFPS manual too. 

Question: are the fire zombies all short? If so, was that on purpose?

What else are you thinking of adding or messing around with?

And what would you like me to focus on? I am planning on adding weapons to various buildings, a ladder or two and fixing the street signs. I was also going to delete all the music files we aren't using. And maybe work on the splash screen (unless you want to do that). 
- Howard

P.S.  I haven't pushed any changes in a while. I'm just fooling around and trying things out here and there, but I don't save any of it. Nothing critical or amazing has been lost. I'll push again when I do something substantial.

On Jan 23, 2016, at 3:29 PM, mwbullen notifications@github.com wrote:

You can view, comment on, or merge this pull request online at:

  https://github.com/BHD7/Ghost_Town_FPS_Zombies/pull/5

Commit Summary

Revised weapon pickups
Added new fire zombie enemy
Changes
Added day/night number display
Gamecontrol tracks # of enemies killed
Adding game end display
Adding Game end UI, issue with mouse cursor not appearing
File Changes

M Ghost Town + UFPS + Zombies/Assembly-CSharp.csproj (1)
A Ghost Town + UFPS + Zombies/Assets/MouseControl.cs (20)
A Ghost Town + UFPS + Zombies/Assets/MouseControl.cs.meta (12)
M Ghost Town + UFPS + Zombies/Assets/Plugins/PlayMaker/Resources/PlayMakerGlobals.asset (0)
A Ghost Town + UFPS + Zombies/Assets/Prefabs/Enemies.meta (9)
A Ghost Town + UFPS + Zombies/Assets/Prefabs/Enemies/FireZombie.prefab (0)
A Ghost Town + UFPS + Zombies/Assets/Prefabs/Enemies/FireZombie.prefab.meta (8)
R Ghost Town + UFPS + Zombies/Assets/Prefabs/Enemies/Zombie.prefab (0)
R Ghost Town + UFPS + Zombies/Assets/Prefabs/Enemies/Zombie.prefab.meta (0)  
R Ghost Town + UFPS + Zombies/Assets/Prefabs/Pickups/Chest -Big.prefab (0)
R Ghost Town + UFPS + Zombies/Assets/Prefabs/Pickups/Chest -Big.prefab.meta     (0)
R Ghost Town + UFPS + Zombies/Assets/Prefabs/Pickups/Chest-Pistol.prefab (0)
R Ghost Town + UFPS + Zombies/Assets/Prefabs/Pickups/Chest-Pistol.prefab.meta (0)
M Ghost Town + UFPS + Zombies/Assets/UFPS/Base/Content/Prefabs/Pickups/WeaponsHD/Ammo/PickupAssaultRifle01Clip.prefab (0)
M Ghost Town + UFPS + Zombies/Assets/UFPS/Base/Content/Prefabs/Pickups/WeaponsHD/Ammo/PickupPistol01Clip.prefab (0)
M Ghost Town + UFPS + Zombies/Assets/UFPS/Base/Content/Prefabs/Pickups/WeaponsHD/PickupAssaultRifle01.prefab (0)
M Ghost Town + UFPS + Zombies/Assets/UFPS/Base/Content/Prefabs/Pickups/WeaponsHD/PickupPistol01.prefab (0)
M Ghost Town + UFPS + Zombies/Assets/UFPS/Base/Content/Prefabs/Pickups/WeaponsHD/PickupShotgun01.prefab (0)
M Ghost Town + UFPS + Zombies/Assets/UFPS/Base/Content/Prefabs/Players/HeroHDWeapons.prefab (0)
M Ghost Town + UFPS + Zombies/Assets/UFPS/Base/Scripts/Gameplay/Inventory/vp_ItemPickup.cs (2)
M Ghost Town + UFPS + Zombies/Assets/UFPS/Base/Scripts/Gameplay/Player/Local/vp_FPPlayerDamageHandler.cs (2)
M Ghost Town + UFPS + Zombies/Assets/main_scene-1.unity (0)
M Ghost Town + UFPS + Zombies/Library/CurrentLayout.dwlt (0)
M Ghost Town + UFPS + Zombies/Library/CurrentMaximizeLayout.dwlt (0)
M Ghost Town + UFPS + Zombies/Library/ScriptAssemblies/Assembly-CSharp-Editor.dll (0)
M Ghost Town + UFPS + Zombies/Library/ScriptAssemblies/Assembly-CSharp-Editor.dll.mdb (0)
M Ghost Town + UFPS + Zombies/Library/ScriptAssemblies/Assembly-CSharp-firstpass.dll (0)
M Ghost Town + UFPS + Zombies/Library/ScriptAssemblies/Assembly-CSharp-firstpass.dll.mdb (0)
M Ghost Town + UFPS + Zombies/Library/ScriptAssemblies/Assembly-CSharp.dll (0)
M Ghost Town + UFPS + Zombies/Library/ScriptAssemblies/Assembly-CSharp.dll.mdb (0)
M Ghost Town + UFPS + Zombies/Library/ScriptAssemblies/Assembly-UnityScript-firstpass.dll (0)
M Ghost Town + UFPS + Zombies/Library/ScriptAssemblies/Assembly-UnityScript-firstpass.dll.mdb     (0)
M Ghost Town + UFPS + Zombies/Library/assetDatabase3 (0)
M Ghost Town + UFPS + Zombies/Library/expandedItems (0)
M Ghost Town + UFPS + Zombies/Library/metadata/00/00000000000000003000000000000000 (0)
M Ghost Town + UFPS + Zombies/Library/metadata/00/00000000000000004000000000000000 (0)
M Ghost Town + UFPS + Zombies/Library/metadata/00/00000000000000006100000000000000 (0)
M Ghost Town + UFPS + Zombies/Library/metadata/5e/5e5834f891ba5f44c929767bb50880b2.info (0)
M Ghost Town + UFPS + Zombies/Library/metadata/6f/6f91aed317ae6e5468fc28c3ad0fb2cd.info (0)
M Ghost Town + UFPS + Zombies/Library/metadata/88/8814e500adaf70c4ca95b44fcf733c3a (0)
M Ghost Town + UFPS + Zombies/Library/metadata/ba/ba4f894b1d48441489eaff30ea6ec9a9 (0)
M Ghost Town + UFPS + Zombies/Library/metadata/ba/ba4f894b1d48441489eaff30ea6ec9a9.info (0)
M Ghost Town + UFPS + Zombies/Library/metadata/d4/d45c3caadb0dedb45909441e14a8de7b (0)
M Ghost Town + UFPS + Zombies/Library/metadata/f4/f4954ef8413e16c43a6a83a7310140cb.info (0)
Patch Links:

https://github.com/BHD7/Ghost_Town_FPS_Zombies/pull/5.patch
https://github.com/BHD7/Ghost_Town_FPS_Zombies/pull/5.diff

**Comment by mwbullen** [comment]
Hey,
I turned the day time down for testing and forgot to put it back. It's on
the game control object if you want to change it back.
Yes please work on the stuff you mentioned if you get a chance. I'll try
and make an exe today too.

Mike

**Comment by mwbullen** [comment]
Very strange, I can't change the time back to 20 seconds.  I change it and
save it and then reload Unity and its right back to 3 seconds.  Weird
I got an .exe that runs by macking this change:
http://answers.unity3d.com/questions/950569/game-runs-in-editor-crashes-on-startup-after-build.html

**Comment by mwbullen** [comment]
OK think I sorted it out

**Pull request merged**
